services:
  postgres:
    image: postgres:latest
    container_name: enquete-postgres
    environment:
      POSTGRES_DB: enquetedb            # Nome do banco para este serviço
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: